name: Rust check

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: >
            cargo fmt --all -- --check
            && cargo install cargo-sort
            && cargo sort --workspace --check --grouped
            && cargo clippy --workspace --tests -- -Dwarnings
            && cargo test --workspace --features runtime-benchmarks
